steps:
  - name: "hashicorp/terraform"
    id: terraform-deploy-apply
    script: |
      terraform -chdir=infra/deployment/terraform/deploy/envs/${ENVIRONMENT} init -backend-config=bucket=$TFSTATE_BUCKET

      terraform -chdir=infra/deployment/terraform/deploy/envs/${ENVIRONMENT} apply -lock-timeout=60m --auto-approve
    env:
      - "TFSTATE_BUCKET=${_TFSTATE_BUCKET}"
      - "TF_VAR_billing_account=${_BILLING_ACCOUNT}"
      - "TF_VAR_org_id=${_ORG_ID}"
      - "TF_VAR_project_id=${PROJECT_ID}"
options:
  logging: CLOUD_LOGGING_ONLY
