steps:
  - name: "hashicorp/terraform"
    id: terraform-org-plan
    dir: infra/terraform/org
    script: |
      terraform init -backend-config=bucket=$TFSTATE_BUCKET

      terraform plan
    env:
      - "TFSTATE_BUCKET=${_TFSTATE_BUCKET}"
      - "TF_VAR_billing_account=${_BILLING_ACCOUNT}"
      - "TF_VAR_org_id=${_ORG_ID}"
      - "TF_VAR_project_id=${PROJECT_ID}"
options:
  logging: CLOUD_LOGGING_ONLY
